# Generated by Django 4.2.5 on 2023-09-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialista', '0002_especialista_direccion_especialista_numero_telefono_and_more'),
        ('paciente', '0004_paciente_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('especialista_primario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_primarias', to='especialista.especialista')),
                ('especialista_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_secundarias', to='especialista.especialista')),
                ('nombre_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
