# Generated by Django 4.2.5 on 2023-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_sangre', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_actuales', models.TextField(blank=True)),
                ('enfermedades_previas', models.TextField(blank=True)),
                ('cirugias_previas', models.TextField(blank=True)),
                ('medico_referente', models.CharField(blank=True, max_length=120)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=120)),
                ('telefono_contacto_emergencia', models.CharField(blank=True, max_length=15)),
                ('relacion_contacto_emergencia', models.CharField(blank=True, max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('seguro_medico', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
