# Generated by Django 4.2.5 on 2023-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
