# Generated by Django 4.2.5 on 2023-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
