# Generated by Django 4.2.5 on 2023-09-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('especialidad', models.CharField(choices=[('PSI', 'Psicólogos'), ('TER', 'Terapia ocupacional'), ('FON', 'Fonoaudiología'), ('PSIPE', 'Psicopedagogía'), ('PSIQ', 'Psiquiatría'), ('MAS', 'Masoterapia'), ('TC', 'Terapias complementarias'), ('NUT', 'Nutricionistas'), ('BIO', 'Biodanza')], max_length=10)),
                ('codigo_medico', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
